{
    "scopeName": "source.beancount", 
    "name": "Beancount", 
    "patterns": [
        {
            "comment": "Comments", 
            "match": ";.*", 
            "name": "comment.line.beancount"
        }, 
        {
            "comment": "Tag directive", 
            "beginCaptures": {
                "1": {
                    "name": "support.function.beancount"
                }, 
                "2": {
                    "name": "keyword.operator.tag.beancount"
                }, 
                "3": {
                    "name": "entity.name.tag.beancount"
                }
            }, 
            "begin": "^(poptag|pushtag)\\s+(#)([A-Za-z0-9\\-_/.]+)", 
            "name": "meta.directive.tag.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Include directive", 
            "beginCaptures": {
                "1": {
                    "name": "support.function.beancount"
                }, 
                "2": {
                    "name": "string.quoted.double.beancount"
                }
            }, 
            "begin": "^(include)\\s+(\\\".*\\\")", 
            "name": "meta.directive.include.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Option directive", 
            "beginCaptures": {
                "1": {
                    "name": "support.function.beancount"
                }, 
                "2": {
                    "name": "support.variable.beancount"
                }, 
                "3": {
                    "name": "string.quoted.double.beancount"
                }
            }, 
            "begin": "^(option)\\s+(\\\".*\\\")\\s+(\\\".*\\\")", 
            "name": "meta.directive.option.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Plugin directive", 
            "beginCaptures": {
                "1": {
                    "name": "support.function.beancount"
                }, 
                "2": {
                    "name": "string.quoted.double.beancount"
                }, 
                "3": {
                    "name": "entity.name.function.beancount"
                }, 
                "4": {
                    "name": "string.quoted.double.beancount"
                }
            }, 
            "begin": "^(plugin)\\s+(\\\"(.*)\\\")\\s+(\\\".*\\\")", 
            "name": "keyword.operator.directive.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Open/Close/Pad directive", 
            "beginCaptures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s+(open|close|pad)", 
            "name": "meta.directive.dated.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#account"
                }, 
                {
                    "include": "#commodity"
                }, 
                {
                    "match": "\\,", 
                    "name": "punctuation.separator.beancount"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Event directive", 
            "beginCaptures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.directive.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s(event)", 
            "name": "meta.directive.dated.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#string"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Commodity directive", 
            "beginCaptures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.directive.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s(commodity)", 
            "name": "meta.directive.dated.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#commodity"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Note/Document directive", 
            "beginCaptures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.directive.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s(note|document)", 
            "name": "meta.directive.dated.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#account"
                }, 
                {
                    "include": "#string"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Price directives", 
            "beginCaptures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.directive.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s(price)", 
            "name": "meta.directive.dated.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#commodity"
                }, 
                {
                    "include": "#amount"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Balance directives", 
            "beginCaptures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.directive.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s(balance)", 
            "name": "meta.directive.dated.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#account"
                }, 
                {
                    "include": "#amount"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        {
            "comment": "Transaction directive", 
            "beginCaptures": {
                "8": {
                    "name": "string.quoted.narration.beancount"
                }, 
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }, 
                "6": {
                    "name": "support.function.directive.beancount"
                }, 
                "7": {
                    "name": "string.quoted.tiers.beancount"
                }
            }, 
            "begin": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})\\s+(txn|[*!&amp;#?%PSTCURM])(?:\\s+(\".*\")(?=\\s+\"))?\\s+(\".*?\")(?=((?:\\s+#[a-zA-z\\-]+(?=\\s))*(?:\\s+\\^[a-zA-z\\-\\.]+(?=\\s))*(?:\\s+;\\s*.*)?)\\s)", 
            "name": "meta.directive.transaction.beancount", 
            "end": "(?=(^\\s*$|^\\S))", 
            "patterns": [
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#posting"
                }, 
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#tag"
                }, 
                {
                    "include": "#link"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }
    ], 
    "repository": {
        "cost": {
            "endCaptures": {
                "0": {
                    "name": "keyword.operator.assignment.beancount"
                }
            }, 
            "beginCaptures": {
                "0": {
                    "name": "keyword.operator.assignment.beancount"
                }
            }, 
            "begin": "\\{\\{?", 
            "name": "meta.cost.beancount", 
            "end": "\\}\\}?", 
            "patterns": [
                {
                    "include": "#amount"
                }, 
                {
                    "include": "#date"
                }, 
                {
                    "match": "\\,", 
                    "name": "punctuation.separator.beancount"
                }, 
                {
                    "include": "#illegal"
                }
            ]
        }, 
        "amount": {
            "captures": {
                "1": {
                    "name": "keyword.operator.modifier.beancount"
                }, 
                "2": {
                    "name": "constant.numeric.currency.beancount"
                }, 
                "3": {
                    "name": "entity.type.commodity.beancount"
                }
            }, 
            "match": "([\\-|\\+]?)((?:\\d|\\d[\\d,]*\\d)(?:\\.\\d*)?)\\s*([A-Z][A-Z0-9\\'\\.\\_\\-]{0,22}[A-Z0-9])", 
            "name": "meta.amount.beancount"
        }, 
        "tag": {
            "captures": {
                "1": {
                    "name": "keyword.operator.tag.beancount"
                }, 
                "2": {
                    "name": "entity.name.tag.beancount"
                }
            }, 
            "match": "(?<=\\s)(#)([A-Za-z0-9\\-_/.]+)(?=\\s)"
        }, 
        "link": {
            "captures": {
                "1": {
                    "name": "keyword.operator.link.beancount"
                }, 
                "2": {
                    "name": "markup.underline.link.beancount"
                }
            }, 
            "match": "(?<=\\s)(\\^)([A-Za-z0-9\\-_/.]+)(?=\\s)"
        }, 
        "meta": {
            "end": "\\n", 
            "beginCaptures": {
                "1": {
                    "name": "keyword.operator.directive.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }
            }, 
            "begin": "^\\s*([a-z][A-Za-z0-9\\-]+)([:])\\s", 
            "patterns": [
                {
                    "include": "#string"
                }, 
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#illegal"
                }
            ], 
            "name": "meta.meta.beancount"
        }, 
        "string": {
            "end": "\\\"", 
            "patterns": [
                {
                    "match": "\\\\.", 
                    "name": "constant.character.escape.beancount"
                }
            ], 
            "begin": "\\\"", 
            "name": "string.quoted.double.beancount"
        }, 
        "account": {
            "end": "\\s", 
            "beginCaptures": {
                "1": {
                    "name": "constant.language.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }
            }, 
            "begin": "([A-Z][A-Za-z0-9\\-]+)(:)", 
            "patterns": [
                {
                    "comment": "Sub accounts", 
                    "beginCaptures": {
                        "1": {
                            "name": "variable.account.beancount"
                        }, 
                        "2": {
                            "name": "punctuation.separator.beancount"
                        }
                    }, 
                    "begin": "([A-Z][A-Za-z0-9\\-]+)([:]?)", 
                    "patterns": [
                        {
                            "include": "$self"
                        }, 
                        {
                            "include": "#illegal"
                        }
                    ], 
                    "end": "([:]?)|(\\s)"
                }
            ], 
            "name": "meta.account.beancount"
        }, 
        "flag": {
            "match": "(?<=\\s)([*!&amp;#?%PSTCURM])", 
            "name": "keyword.other.beancount"
        }, 
        "commodity": {
            "match": "([A-Z][A-Z0-9\\'\\.\\_\\-]{0,22}[A-Z0-9])", 
            "name": "entity.type.commodity.beancount"
        }, 
        "comments": {
            "captures": {
                "1": {
                    "name": "comment.line.beancount"
                }
            }, 
            "match": "(?<=\\s)(;.*)(?=\\n)"
        }, 
        "illegal": {
            "match": "[^\\s]", 
            "name": "invalid.illegal.unrecognized.beancount"
        }, 
        "posting": {
            "end": "(?=(^\\s*$|^\\S|^\\s*[A-Z]))", 
            "patterns": [
                {
                    "include": "#meta"
                }, 
                {
                    "include": "#comments"
                }, 
                {
                    "include": "#flag"
                }, 
                {
                    "include": "#account"
                }, 
                {
                    "include": "#amount"
                }, 
                {
                    "include": "#cost"
                }, 
                {
                    "include": "#date"
                }, 
                {
                    "include": "#price"
                }, 
                {
                    "include": "#illegal"
                }
            ], 
            "begin": "^\\s+(?=([A-Z\\!]))", 
            "name": "meta.posting.beancount"
        }, 
        "price": {
            "end": "(?=(;|\\n))", 
            "beginCaptures": {
                "0": {
                    "name": "keyword.operator.assignment.beancount"
                }
            }, 
            "begin": "\\@\\@?", 
            "patterns": [
                {
                    "include": "#amount"
                }, 
                {
                    "include": "#illegal"
                }
            ], 
            "name": "meta.price.beancount"
        }, 
        "date": {
            "captures": {
                "1": {
                    "name": "constant.numeric.date.year.beancount"
                }, 
                "2": {
                    "name": "punctuation.separator.beancount"
                }, 
                "3": {
                    "name": "constant.numeric.date.month.beancount"
                }, 
                "4": {
                    "name": "punctuation.separator.beancount"
                }, 
                "5": {
                    "name": "constant.numeric.date.day.beancount"
                }
            }, 
            "match": "([0-9]{4})([\\-|/])([0-9]{2})([\\-|/])([0-9]{2})", 
            "name": "meta.date.beancount"
        }
    }, 
    "uuid": "dbf28879-ee4d-497e-a678-a5c5a5e8d74f", 
    "fileTypes": [
        "beancount"
    ]
}