<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>beancount</string>
	</array>
	<key>name</key>
	<string>Beancount</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Commented text</string>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.beancount</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Root Accounts</string>
			<key>match</key>
			<string>\s([A-Z][A-Za-z0-9\-]+)(:)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([:]?)([A-Z][A-Za-z0-9\-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.account.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Accounts</string>
			<key>end</key>
			<string>([:]?)|(\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>strings</string>
			<key>match</key>
			<string>\".*\"</string>
			<key>name</key>
			<string>string.quoted.double.beancount</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Directives (no date)</string>
			<key>match</key>
			<string>^(option|poptag|pushtag)\s</string>
			<key>name</key>
			<string>keyword.operator.directive.beancount</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Currencies</string>
			<key>match</key>
			<string>\s([A-Z][A-Z0-9\'\.\_\-]{0,10}[A-Z0-9])[\,?|\s]</string>
			<key>name</key>
			<string>variable.other.currency.beancount</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.builtin.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Dated directives</string>
			<key>match</key>
			<string>([0-9]{4})\-([0-9]{2})\-([0-9]{2})\s(open|close|pad|balance|note|price|event|document)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})\-([0-9]{2})\-([0-9]{2})(\stxn)?\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.builtin.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Transactions</string>
			<key>end</key>
			<string>\s(".*")\s(\|)\s(".*")|\s(".*")\s(".*")|(".*")[\s]*$|([\s]*$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.structure.dictionary.payee.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.narration.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.structure.dictionary.payee.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.narration.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.narration.beancount</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\!</string>
					<key>name</key>
					<string>keyword.operator.flag.beancount</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>keyword.operator.mark.beancount</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>flag</string>
			<key>match</key>
			<string>\!\s</string>
			<key>name</key>
			<string>keyword.other.beancount</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Price assignment</string>
			<key>match</key>
			<string>\@</string>
			<key>name</key>
			<string>keyword.operator.assignment.beancount</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Lot assignment</string>
			<key>match</key>
			<string>\/</string>
			<key>name</key>
			<string>keyword.operator.assignment.beancount</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cost assignment</string>
			<key>match</key>
			<string>\{</string>
			<key>name</key>
			<string>keyword.operator.assignment.beancount</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cost assignment</string>
			<key>match</key>
			<string>\}</string>
			<key>name</key>
			<string>keyword.operator.assignment.beancount</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.tag.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tags and links</string>
			<key>match</key>
			<string>(#)([A-Za-z0-9\-_/.]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Links</string>
			<key>match</key>
			<string>(\^)([A-Za-z0-9\-_/.]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>([\-|\+]?)([\d]+\.[\d]+)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Illegal</string>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.beancount</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.beancount</string>
	<key>uuid</key>
	<string>dbf28879-ee4d-497e-a678-a5c5a5e8d74f</string>
</dict>
</plist>
